### ISSUE TITLE
Clean up front end

### ISSUE THREAD

**Issue by harrisonlingren** [harrisonlingren/myrecipes#19]
Need to clean up the code merged in for the frontend

**Comment by mdsecurity** [comment]
hi can you assign this to me?

**Comment by yukio808** [comment]
I would like to contribute to the project. Can you give me some rundown instructions for pull request preferences, code style and such?

**Comment by harrisonlingren** [comment]
@yukio808 Hi there! If you would like to contribute, feel free to fork this repo and make your changes. As far as code style and all that, I will add another md file to the repo root. This is an extremely new project without real precedents, so PR preferences (at least at this time) can pretty much be summed up as:
Make a PR when you have completed as issue. I will review your contribution and let you know if any changes seem necessary before merging.

**Comment by himanshu81494** [comment]
I would like to work on it

**Comment by harrisonlingren** [comment]
@dhruvdutt @himanshu81494 please feel free to fork this repository to make your contribution. Once you are done, submit a PR back to this repo (develop branch) and I will review your work. See CONTRIBUTING.md for more details
